import { useEffect, useState } from 'react'
import { ArrowLeft, Edit3, Star } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import * as productApi from '../api/products.js'

export default function ProductDetailsPage() {
    const { id } = useParams(); const navigate = useNavigate(); const [product, setProduct] = useState(null); const [image, setImage] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
    useEffect(() => { productApi.getProduct(id).then((data) => { const changes = JSON.parse(localStorage.getItem('nexgensis_changes') || '{}'); const next = { ...data, ...(changes[id] || {}) }; setProduct(next); setImage(next.images?.[0] || next.thumbnail) }).catch((reason) => setError(reason.message)).finally(() => setLoading(false)) }, [id])
    if (loading) return <div className="table-loader"><span className="loader-ring" /></div>
    if (error || !product || !Number.isInteger(Number(id))) return <div className="error-state"><h3 className="state-title">Product not found</h3><p className="state-copy">That product does not exist in the catalog.</p><button className="soft-btn" onClick={() => navigate('/products')}><ArrowLeft size={14} /> Back to products</button></div>
    return <><div className="topline"><div><Link className="eyebrow" to="/products">← Back to products</Link><h1 className="page-title">Product details</h1></div><Link className="soft-btn" to={`/products/${product.id}/edit`}><Edit3 size={14} /> Edit product</Link></div><div className="detail-grid"><div className="detail-media"><img className="detail-main-image" src={image} alt={product.title} /><div className="thumb-list">{(product.images?.length ? product.images : [product.thumbnail]).map((source) => <img key={source} className={`detail-thumb ${source === image ? 'active' : ''}`} src={source} alt="" onClick={() => setImage(source)} />)}</div></div><div className="detail-info"><span className="category-pill">{product.category}</span><h1>{product.title}</h1><p className="detail-description">{product.description}</p><div className="detail-price">${product.price.toFixed(2)}</div><div className="rating">★ {product.rating?.toFixed(1)} customer rating</div><div className="meta-grid"><div><span className="meta-label">Brand</span><span className="meta-value">{product.brand || 'Nexgensis'}</span></div><div><span className="meta-label">Stock</span><span className="meta-value">{product.stock} units</span></div><div><span className="meta-label">Discount</span><span className="meta-value">{product.discountPercentage?.toFixed(1)}%</span></div></div><div className="reviews"><h3>Recent reviews</h3>{(product.reviews || []).slice(0, 3).map((review, index) => <div className="review" key={`${review.reviewerName}-${index}`}><span className="rating"><Star size={12} fill="currentColor" /> {review.rating}/5 · {review.reviewerName}</span><p>{review.comment}</p></div>)}</div></div></div></>
}